First commit for bfe ingress controller
bfenetworks/ingress-bfe pull request #3
Opened 2021-08-12 10:06 UTC by zhugelianglongming

Signed-off-by: zhugelianglongming <zhugelianglongming@163.com>

2021-08-13 07:41 UTC, mileszhang2016 commented on docs/zh_cn/ingress/priority.md
> +- 域名、路径径相同、匹配条件个数相同情况下，按照匹配条件的固定顺序确定优先级；
路径径相同 => 路径相同

2021-08-13 08:20 UTC, zhugelianglongming commented on docs/zh_cn/ingress/priority.md
> +- 域名、路径径相同、匹配条件个数相同情况下，按照匹配条件的固定顺序确定优先级；
已更正

2021-08-16 07:03 UTC, iyangsj commented on LICENSE
> -
Licence文件修改回滚掉

2021-08-16 07:06 UTC, iyangsj commented on cmd/bfe_ingress_controller/main.go
> +
多余的空格

2021-08-16 07:07 UTC, iyangsj commented on dist/bfe.ini
> +command=./go_bfe -c ../conf -l ../log -d
go-bfe统一替换为 bfe ？

2021-08-16 07:07 UTC, iyangsj commented on dist/start.sh
> +readonly BFE_BIN=go_bfe
文件中的go-bfe统一替换为bfe ？

2021-08-16 07:10 UTC, iyangsj commented on internal/bfe_ingress/ingress.go
> +// Copyright (c) 2021 The BFE Authors.
internal/.DS_Store 文件不需要提交到仓库

2021-08-16 07:11 UTC, iyangsj commented on internal/bfe_ingress/ingress.go
> +import (
import风格建议和 bfe项目保持一致（分为多个import段：标准包，第三方包，自有包）

2021-08-16 07:11 UTC, iyangsj commented on internal/bfe_ingress/ingress.go
> +	client, _ := kubernetes_client.NewKubernetesClient()
应该处理返回值的错误？

2021-08-16 07:14 UTC, iyangsj commented on internal/bfe_ingress/watcher.go
> +						serviceName := path.Backend.ServiceName
嵌套的层次太深

2021-08-16 07:14 UTC, iyangsj commented on internal/bfe_ingress/watcher.go
> +			iw.ingressCh <- ingresses
增加空行

2021-08-16 07:14 UTC, iyangsj commented on internal/builder/annotation.go
> +// cookieAnnotation.Check; cookie annotation's valid str is "key: value"
注释风格（已Check 开头的完整句子）

2021-08-16 07:15 UTC, iyangsj commented on internal/builder/annotation.go
> +// headerAnnotation.Check; cookie annotation's valid str is "key: value"
同上，注释风格

2021-08-16 07:18 UTC, iyangsj commented on cmd/bfe_ingress_controller/main.go
> +	return ""
这里为什么返回无意义的空？

2021-08-16 07:57 UTC, iyangsj requested changes

2021-08-16 07:57 UTC, iyangsj commented on cmd/bfe_ingress_controller/main.go
> +
建议基础类型 移动到 common之类的包中

2021-08-16 07:57 UTC, iyangsj commented on cmd/bfe_ingress_controller/main.go
> +	bfe_ingress.NewBfeIngress(namespaces, labels, *ingressClass).Start()
不建议使用链式风格

2021-08-16 07:57 UTC, iyangsj commented on go.sum
> +bou.ke/monkey v1.0.2 h1:kWcnsrCNUatbxncxR/ThdYqbytgOIArtYWqcQLQzKLI=
试试执行 go mod tidy再提交这个文件

2021-08-16 07:57 UTC, iyangsj commented on internal/bfe_ingress/ingress.go
> +	<-ing.stopCh
这里 Start() 函数可能会早于 watcher/process 退出，导致未优雅处理退出？

2021-08-16 07:57 UTC, iyangsj commented on internal/bfe_ingress/ingress.go
> +	time.Sleep(time.Second)
sleep()操作不应该在这里控制

2021-08-16 07:57 UTC, iyangsj commented on internal/bfe_ingress/watcher.go
> +	if iw.client == nil || iw.ingressCh == nil || iw.stopCh == nil {
避免用panic风格处理异常

2021-08-16 07:57 UTC, iyangsj commented on internal/bfe_ingress/processer.go
> +	time.Sleep(30 * time.Second)
这里为什么要固定等待 30s

2021-08-16 07:57 UTC, iyangsj commented on internal/bfe_ingress/processer.go
> +func (p *Processor) preProcessIngresses(ingresses ingressList) {
建议函数名直接改为 sortIngresses

2021-08-17 10:57 UTC, zhugelianglongming commented on LICENSE
> -
Done

2021-08-23 05:26 UTC, iyangsj requested changes

2021-08-23 05:28 UTC, iyangsj commented on internal/builder/reload.go
> +
这里应该返回错误？（状态码非200）

2021-08-24 09:19 UTC, zhugelianglongming commented on internal/builder/reload.go
> +
应返回错误，已修正

2021-09-02 07:53 UTC, iyangsj requested changes

2021-09-02 07:53 UTC, iyangsj commented on internal/builder/balance_builder.go
> +
多余的空行

2021-09-02 07:53 UTC, iyangsj commented on internal/builder/balance_builder.go
> +		for _, addr := range subsets.Addresses {
建议将 line 306～330封装为函数

2021-09-02 07:53 UTC, iyangsj commented on internal/builder/balance_builder.go
> +}
空行

2021-09-02 07:53 UTC, iyangsj commented on internal/builder/balance_builder.go
> +		namespace := strings.Split(key, "_")[0]
line 259 封装为函数，与相关的集群名操作放在一起

2021-09-02 07:53 UTC, iyangsj commented on internal/builder/balance_builder.go
> +
建议相关的配置设置放在一起
line 222 移动到line 231，line223～224 移动到line 237

2021-09-02 07:53 UTC, iyangsj commented on internal/builder/balance_builder.go
> +	for key, subClusters := range c.clusters {
key建议改为 clusterName

2021-09-02 07:53 UTC, iyangsj commented on internal/builder/builder.go
> +
各接口方法增加必要的注释

2021-09-02 07:53 UTC, iyangsj commented on cmd/bfe_ingress_controller/main.go
> +func initIngressParams() {
建议去除不必要的全局变量
1. util中定义为常量
2. 各命令行参数以参数形式传递到所需结构

2021-09-02 07:53 UTC, iyangsj commented on internal/builder/route_builder.go
> +			if len(routeRuleFile.RawRuleInfo.Annotations) <= 0 {
建议line318～line341封装为函数

2021-09-02 08:46 UTC, zhugelianglongming commented on internal/builder/route_builder.go
> +	defaultHashHeader := "Cookie: bfe_userid"
修改与github.com/bfenetworks/bfe/bfe_balance/bal_gslb/bal_gslb.go:NewBalanceGslb() 一致

2021-09-02 17:43 UTC, zhugelianglongming commented on internal/builder/tls_config_builder.go
> +	c.tc.tlsRuleConf = tr
请教下，多证书需要在哪里显示设置？

2021-09-03 06:28 UTC, zhugelianglongming commented on internal/builder/tls_config_builder.go
> +	c.tc.tlsRuleConf = tr
修改为显式设置SNI conf， cert name

2021-09-08 08:08 UTC, iyangsj approved these changes
初始提交版本，待迭代优化

2021-09-08 08:09 UTC, merged