support redirect
bfenetworks/ingress-bfe pull request #72
Opened 2022-07-13 05:37 UTC by loheagn

Signed-off-by: loheagn <loheagn@icloud.com>

2022-07-15 04:46 UTC, zhugelianglongming requested changes

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/redirect.go
> +	"errors"
建议按照以下分组：
库包
其他第三方库包
本代码库包

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/redirect.go
> +func GetRedirectAction(annotations map[string]string) (*mod_redirect.ActionFile, error) {
建议按照 Annotaion 维度获取，使函数功能简化、单一。
逻辑对象的拼接可以在config 的调用包中执行。

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/redirect.go
> +	RedirectURLSetAnnotation       = redirectAnnotationPrefix + "url-set"
建议注释说明，这是一类相关的 Annotation（用于设置 redirect 的 Location)

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/redirect.go
> +	annotationList := []string{RedirectURLSetAnnotation, RedirectURLFromQueryAnnotation, RedirectURLPrefixAddAnnotation, RedirectSchemeSetSetAnnotation}
补充单个 Location 类 Annotation 的检验逻辑

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/redirect.go
> +	statusCodeInt := 302
302 建议抽取为常量。如 DefaultRedirectResponseStatus

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/redirect.go
> +	statusCodeInt = int(statusCodeInt64)
补充 status 值校验逻辑

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/redirect.go
> +	if err != nil {
Int 解析失败为何返回 error 为 nil？

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache.go
> +import (
建议分组同上

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache.go
> +type HttpRuleCache interface {
建议抽象 Cache 与 Rule

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/configs/module.go
> +	UpdateIngress(ingress *netv1.Ingress) error
建议添加注释说明用途与注意事项

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/configs/redirect.go
> +	ok, err := annotations.RedirectPreCheck(ingress.Annotations)
`redirectEnable` 或者 `enabled` 会不会比 `ok` 更有可读性？

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/configs/redirect.go
> +	srcBasicRuleList, advancedRuleList := r.redirectRuleCache.GetHttpRules()
Redirect 规则需要区分 basic 和 advance 么？

2022-07-15 04:46 UTC, zhugelianglongming commented on internal/bfeConfig/configs/redirect.go
> +
dump 失败的处理行为是什么？

2022-07-15 04:46 UTC, zhugelianglongming commented on test/e2e/e2e_test.go
> +	"github.com/bfenetworks/ingress-bfe/test/e2e/steps/annotations/redirect"
Import分组，同上

2022-07-21 02:44 UTC, zhugelianglongming requested changes

2022-07-21 02:44 UTC, zhugelianglongming commented on internal/bfeConfig/configBuilder.go
> +	"github.com/bfenetworks/ingress-bfe/internal/bfeConfig/configs/modules"
import 分组

2022-07-21 02:44 UTC, zhugelianglongming commented on internal/bfeConfig/configBuilder.go
> +			c.serverDataConf.DeleteIngress(ingress.Namespace, ingress.Name)
tlsConf 也需要回滚

2022-07-21 02:44 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache/baseCache.go
> +		return nil
为什么这里返回为 nil？

2022-07-21 02:44 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache/baseCache.go
> +		return ruleList[i].Compare(ruleList[j])
不同类型 rule 之间优先级的比较逻辑预期是一致的

2022-07-21 03:50 UTC, zhugelianglongming requested changes

2022-07-21 03:50 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache/baseCache.go
> +func (c *BaseCache) DeleteRulesByIngress(ingress string) {
UpdateByIngress 
DeleteRulesByIngress
建议统一命名风格

2022-07-21 03:50 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache/baseCache.go
> +func (c *BaseCache) UpdateByIngressFramework(ingress *netv1.Ingress, beforeUpdate func() (bool, error), newRuleFunc BuildRuleFunc, afterUpdate func() error) error {
1. 建议这几个函数入参的类型，可以定义个名字，便于记忆和使用，提高可读性
2. 建议支持默认参数 nil，便于无响应行为的场景的调用。

2022-07-21 03:50 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache/baseCache.go
> +	if _, ok := c.RuleMap[rule.GetHost()]; !ok {
频繁调用 `rule.GetHost()`，`rule.GetPath()`
建议缓存结果优化

2022-08-03 11:25 UTC, zhugelianglongming requested changes

2022-08-03 11:25 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache/baseCache.go
> +
推荐添加注释说明
特别是说明获得的 Rule 列表已根据统一的路由规则完成排序，优先级最高的 Rule 在列表的什么位置。

注释有利于调用者在选择是否调用这个函数时做决策、或者快速排查问题。

2022-08-03 11:25 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache/baseCache.go
> +	ingress *netv1.Ingress,
1. 这个 3 变量的为什么名字的格式不太统一？
2. newRuleFunc 添加nil 校验
3. 个人建议：Func 偏向表形式，倾向在类名中表述；Hook 偏向表意，倾向在变量名中表述

2022-08-03 11:25 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache/cache.go
> +// Copyright (c) 2022 The BFE Authors.
这个文件的作用是？

2022-08-03 11:25 UTC, zhugelianglongming commented on internal/bfeConfig/configs/modules/redirect/cache.go
> +	statusCode int
建议添加注释说明字段，比如含义、注意事项等

2022-08-03 11:25 UTC, zhugelianglongming commented on internal/bfeConfig/configs/modules/redirect/cache.go
> +		func() error {
这个函数是不是替换为 nil 更方便？

2022-08-03 11:25 UTC, zhugelianglongming commented on internal/bfeConfig/configs/cache/baseCache.go
> +type BeforeUpdateIngressHook func() (bool, error)
建议添加注释说明 用法，比如 bool true 和 false 分别代表后续会被如何处理。

2022-08-03 11:25 UTC, zhugelianglongming commented on internal/bfeConfig/configs/modules/redirect/redirect.go
> +func (r *ModRedirectConfig) updateRedirectConfFile() error {
这个redirectConfFile 是不是会导致更新的太过频繁。
如果有 1w 条规则，每条变更 1 次，redirectConfFile需要生成 1w 次，并且 Rule 校验要进行 1w条*1w 次。

如果在 reload 前进行 ConfFile 的更新，是不是更优化? 1 次生成，1w 条*次 Rule 校验

2022-08-05 08:43 UTC, zhugelianglongming requested changes
核心建议优化 ConfFile 的生成性能
其他建议主要是

2022-08-05 08:43 UTC, zhugelianglongming commented on internal/bfeConfig/configs/modules/redirect/redirect.go
> +func (r *ModRedirectConfig) updateRedirectConfFile() error {
主要是同一条规则，可能在 reload 之前，被重复生成&校验，重复次数相当于期间所有 ingress 的更新数。而这部分重复计算应该可以避免。

2022-08-05 08:43 UTC, zhugelianglongming commented on internal/bfeConfig/configs/modules/redirect/redirect.go
> +	annotationList := []string{annotations.RedirectURLSetAnnotation, annotations.RedirectURLFromQueryAnnotation, annotations.RedirectURLPrefixAddAnnotation, annotations.RedirectSchemeSetSetAnnotation}
建议换行，提高可读性

2022-08-05 08:43 UTC, zhugelianglongming commented on internal/bfeConfig/configs/modules/redirect/redirect.go
> +func parseRedirectActionFromAnnotations(annots map[string]string) (*mod_redirect.ActionFileList, int, error) {
建议添加函数的注释，特别是说明返回值的含义。

2022-08-05 08:43 UTC, zhugelianglongming commented on internal/bfeConfig/configs/serverDataConfig.go
>  	if err := c.updateRouteTable(); err != nil {
既然在 reload 前保证了会有变化的更新 Conf File，这里是不是不需要每次 UpdateIngress 时都更新 Conf File。

2022-08-05 08:43 UTC, zhugelianglongming commented on internal/bfeConfig/configs/serverDataConfig.go
updateBfeClusterConf 同上

2022-08-05 08:43 UTC, zhugelianglongming commented on internal/bfeConfig/configs/serverDataConfig.go
> +		if err := c.updateRouteTable(); err != nil {
Good。 性能上有了提升空间，正确性也有了保证。

2022-08-05 08:43 UTC, zhugelianglongming commented on test/e2e/e2e_test.go
>  	"github.com/bfenetworks/ingress-bfe/test/e2e/steps/annotations/route/header"
建议其他的 import 分组一起调整下顺序。

2022-08-08 02:01 UTC, zhugelianglongming approved these changes
功能符合预期，代码风格和注释建议再优化。

2022-08-08 08:07 UTC, loheagn commented on internal/bfeConfig/configs/serverDataConfig.go
> +		if err := c.updateRouteTable(); err != nil {
Thanks

2022-08-08 09:08 UTC, loheagn commented on internal/bfeConfig/configs/serverDataConfig.go
同上

2022-08-08 09:17 UTC, loheagn commented on internal/bfeConfig/configs/serverDataConfig.go
>  	if err := c.updateRouteTable(); err != nil {
在之前的设计中，更新一个ingress，会把该ingress的所有rule都加到cache中，并对cache中所有rule进行排序，然后将这个排序后的cache更新到confFile结构体中。这一过程虽然有重复计算，但保证了如果当前这个被更新的ingress有错的话，可以在“更新到confFile结构体”这个过程中及时发现错误，并返回给reconciler，更新到ingress的status中。

而如果我们在更新该ingress的时候，仅将其rule信息更新到cache就返回的话，则无法及时返回给ingress的status，有些错误就只有在reload阶段被发现，而这时发现的错误无法准确定位是哪个ingress引起的。

所以这就要求我们在更新ingress到cache时，同时检查插入的Rule的合法性。这个操作在Redirect模块是容易做到的。但是对于Route模块，在校验合法性时，需要涉及到其他Route Rule，整个过程会比较负责。因此，这里先留一个TODO，等待后续解决。

2022-08-08 09:25 UTC, zhugelianglongming approved these changes
优化注释说明

2022-08-08 10:26 UTC, merged

2022-08-12 03:03 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/redirect.go
> +func GetRedirectAction(annotations map[string]string) (cmd, param string, err error) {
这些函数的单测需要补充下