Feat: supprt URL rewrite
bfenetworks/ingress-bfe pull request #82
Opened 2022-11-28 07:31 UTC by mengtao97

使用Annotation方式支持URL重写配置
添加URL重写功能的相关e2e测试
fix https://github.com/bfenetworks/ingress-bfe/issues/54

Signed-off-by: Tao Meng [mtttt1997@gmail.com](https://github.com/bfenetworks/ingress-bfe/issues/mtttt1997@gmail.com)

2022-12-02 02:54 UTC, xuleiming commented on internal/bfeConfig/configs/modules/rewrite/cache.go
> +	cond map[string]string
这个 cond 定义不明确。没有用应该去掉

2022-12-02 02:54 UTC, xuleiming commented on internal/bfeConfig/configs/modules/rewrite/rewrite.go
> +		(*rewriteConfFile.Config)[seg] = &rules
目前开源引擎不支持 hook 点，如果支持的话应该是在 product 之上再加一层，product 仍然保留。此处代码目前的效果也是对的，但是看起来是借用了 product 的位置，以后升级也不方便吧。

2022-12-05 08:32 UTC, zhugelianglongming requested changes
1. 建议 review 设计
2. go 代码需添加单测

2022-12-05 08:32 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/rewrite.go
> +func transRewriteAnnotationKeyToAction(annot string) (ac string) {
这里没有使用 map 实现的主要考虑是什么？
为什么需要这样一层 string 到 string 的映射？

2022-12-05 08:32 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/rewrite.go
> +package annotations
所有go 代码对应的单测代码呢？

2022-12-05 08:32 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/rewrite.go
> +	if _, err := url.Parse(path); err != nil {
return url.Parse(path)

2022-12-05 08:32 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/rewrite.go
> +func parseActionParam(cmd, param string) ([]string, error) {
这个函数的实现太长了，不同指令的校验参数可以抽取成独立函数。
指令和校验函数的映射关系也可以考虑使用 map 管理，进一步进化代码。

2022-12-05 08:32 UTC, zhugelianglongming commented on internal/bfeConfig/annotations/rewrite.go
> +		if param == "" || strings.ToLower(param) != "true" && strings.ToLower(param) != "t" {
这部分为什么需要设置参数为 json 中的 true/t？
https://github.com/bfenetworks/ingress-bfe/issues/54#issuecomment-1336907008

2023-01-12 09:22 UTC, merged

2023-01-13 07:29 UTC, zhugelianglongming commented on test/e2e/steps/annotations/rewrite/steps.go
> +	"github.com/cucumber/godog"
Import预期按来源分组